server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://172.16.50.220:3306/zglu_sys
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

  redis:
    host: 172.16.50.199
    port: 6379
    database: 15

  data:
    solr:
      host: http://172.16.50.199:8983/solr

  thymeleaf:
    cache: false

custom:
  mq:
    url: http://1505716954562220.mqrest.cn-qingdao-public.aliyuncs.com
    id: LTAIfcYYTpu5nhlg
    key: WJpM378JiEfyQOJ98rc4OHKnvwFLpE
    topic: JIUXIAOER-DEFAULT-DEV
    groupId: GID_JIUXIAOER_DEFAULT_DEV
