custom:
  mq:
    url: http://xxxxxxxxxxxx.xxxxxx.cn-xxxxx-xxxxx.aliyuncs.com
    id: axxxxxxxxxxxxx
    key: cdfxxxxxxxxxxxxxxxxxxxxxx
    topic: JXXXXXEEEEERRRRR-FFFEEEEE-DEV
    groupId: GXXXXX_FEESSSSS_XXXXXXXXXX_DEV
