custom:
  mq:
    url: http://xxxxxxxxxxxx.xxxxxx.cn-xxxxx-xxxxx.aliyuncsxx.xxx
    id: axxxxxxxxxxxxxxx
    key: cdfxxxxxxxxxxxxxxxxxxxxxxxx
    topic: JXXXXXEEEEERRRRR-FFFEEEEE-DEV
    groupId: GXXXXX_FEESSSSS_XXXXXXXXXX_DEV
